import Stripe from 'stripe';

export const invoice: Stripe.Invoice = {
  id: 'inv_12345',
  object: 'invoice',
  amount_due: 128905798012,
  amount_paid: 0,
  amount_remaining: 128905798012,
  attempt_count: 0,
  attempted: false,
  collection_method: 'charge_automatically',
  created: 1643415079,
  currency: 'USD',
  customer: 'cus_123456',
  customer_address: {
    line1: '750 Lincoln Way St.',
    line2: '100',
    city: 'Auburn',
    state: 'CA',
    postal_code: '95603',
    country: 'US',
  },
  customer_email: 'tester@example.com',
  customer_name: 'Test Customer',
  default_tax_rates: [],
  lines: {
    object: 'list',
    has_more: false,
    data: [],
    url: 'https://example.com/test',
  },
  livemode: false,
  metadata: {},
  paid: false,
  period_end: 1643415079,
  period_start: 1643415078,
  post_payment_credit_notes_amount: 0,
  pre_payment_credit_notes_amount: 0,
  starting_balance: 0,
  status: 'draft',
  subtotal: 0,
  total: 128905798012,
  total_tax_amounts: [],

  account_country: null,
  account_name: null,
  account_tax_ids: null,
  automatic_tax: {
    enabled: false,
    status: null,
  },
  application_fee_amount: null,
  billing_reason: null,
  charge: null,
  custom_fields: null,
  customer_phone: null,
  customer_shipping: null,
  customer_tax_exempt: null,
  default_payment_method: null,
  default_source: null,
  description: null,
  discount: null,
  discounts: null,
  due_date: null,
  ending_balance: null,
  footer: null,
  last_finalization_error: null,
  next_payment_attempt: null,
  number: null,
  on_behalf_of: null,
  payment_intent: null,
  payment_settings: {
    payment_method_options: null,
    payment_method_types: null,
  },
  quote: null,
  receipt_number: null,
  statement_descriptor: null,
  status_transitions: {
    finalized_at: null,
    marked_uncollectible_at: null,
    paid_at: null,
    voided_at: null,
  },
  subscription: null,
  tax: null,
  total_discount_amounts: null,
  transfer_data: null,
  webhooks_delivered_at: null,
};