import Stripe from 'stripe';

export const invoice: Stripe.Invoice = {
  id: 'inv_12345',
  object: 'invoice',
  amount_due: 128905798012,
  amount_paid: 0,
  amount_remaining: 128905798012,
  attempt_count: 0,
  attempted: false,
  collection_method: 'charge_automatically',
  created: 1643415079,
  currency: 'USD',
  customer: 'cus_123456',
  customer_address: {
    line1: '750 Lincoln Way St.',
    line2: '100',
    city: 'Auburn',
    state: 'CA',
    postal_code: '95603',
    country: 'US',
  },
  customer_email: 'tester@example.com',
  customer_name: 'Test Customer',
  default_tax_rates: [],
  lines: {
    object: 'list',
    has_more: false,
    data: [],
    url: 'https://example.com/test',
  },
  livemode: false,
  metadata: {},
  paid: false,
  period_end: 1643415079,
  period_start: 1643415078,
  post_payment_credit_notes_amount: 0,
  pre_payment_credit_notes_amount: 0,
  starting_balance: 0,
  status: 'draft',
  subtotal: 0,
  total: 128905798012,
  total_tax_amounts: [],

  account_country: null,
  account_name: null,
  account_tax_ids: null,
  automatic_tax: {
    enabled: false,
    status: null,
  },
  application_fee_amount: null,
  billing_reason: null,
  charge: null,
  custom_fields: null,
  customer_phone: null,
  customer_shipping: null,
  customer_tax_exempt: null,
  default_payment_method: null,
  default_source: null,
  description: null,
  discount: null,
  discounts: null,
  due_date: null,
  ending_balance: null,
  footer: null,
  last_finalization_error: null,
  next_payment_attempt: null,
  number: null,
  on_behalf_of: null,
  payment_intent: null,
  payment_settings: {
    payment_method_options: null,
    payment_method_types: null,
  },
  quote: null,
  receipt_number: null,
  statement_descriptor: null,
  status_transitions: {
    finalized_at: null,
    marked_uncollectible_at: null,
    paid_at: null,
    voided_at: null,
  },
  subscription: null,
  tax: null,
  total_discount_amounts: null,
  transfer_data: null,
  webhooks_delivered_at: null,
};

// From https://stripe.com/docs/api/invoiceitems/object
export const invoiceItem: Stripe.InvoiceItem = {
  "id": "ii_1KHx3lFRwUQjTSJENXxLe2lK",
  "object": "invoiceitem",
  "amount": 2405,
  "currency": "usd",
  "customer": "cus_K6yd2CbXLO9A5G",
  "date": 1642194705,
  "description": "Cat toys",
  "discountable": true,
  "discounts": [],
  "invoice": "in_1KGDqDFRwUQjTSJE77nIaZi1",
  "livemode": false,
  "metadata": {},
  "period": {
    "end": 1642194705,
    "start": 1642194705
  },
  plan: null,
  "price": {
    "id": "price_1KHx3lFRwUQjTSJElZUZGmwr",
    "object": "price",
    "active": false,
    "billing_scheme": "per_unit",
    "created": 1642194705,
    "currency": "usd",
    "livemode": false,
    "lookup_key": null,
    "metadata": {},
    "nickname": null,
    "product": "prod_KxspvftVjMxZdO",
    "recurring": null,
    "tax_behavior": "unspecified",
    "tiers_mode": null,
    "transform_quantity": null,
    "type": "one_time",
    "unit_amount": 2405,
    "unit_amount_decimal": "2405"
  },
  "proration": false,
  "quantity": 1,
  "subscription": null,
  "tax_rates": [],
  "unit_amount": 2405,
  "unit_amount_decimal": "2405"
};

// From https://goshippo.com/docs/reference#transactions-create
export const shippoTransaction = {
  "object_state":"VALID",
  "status":"SUCCESS",
  "object_created":"2014-07-25T02:09:34.422Z",
  "object_updated":"2014-07-25T02:09:34.513Z",
  "object_id":"ef8808606f4241ee848aa5990a09933c",
  "object_owner":"shippotle@goshippo.com",
  "test":true,
  "rate":"ee81fab0372e419ab52245c8952ccaeb",
  "tracking_number":"",
  "tracking_status":"UNKNOWN",
  "tracking_history": [],
  "tracking_url_provider":"",
  "eta":"",
  "label_url":"",
  "commercial_invoice_url": "",
  "messages":[

  ],
  "order": null,
  "metadata":"",
  "parcel": null,
  "billing": {
      "payments": []
  },
  "qr_code_url":""
};    

// From https://goshippo.com/docs/reference#shipments
export const shippoShipment = {
  "object_created":"2014-07-17T00:04:06.163Z",
  "object_updated":"2014-07-17T00:04:06.163Z",
  "object_id":"89436997a794439ab47999701e60392e",
  "object_owner":"shippotle@goshippo.com",
  "status":"SUCCESS",
  "address_from":{
     "object_id": "fdabf0abb93c4460b60aa596116872a7",
     "validation_results": {},
     "is_complete": true,
     "name": "Mrs Hippo",
     "company": "Shippo",
     "street_no": "",
     "street1": "1092 Indian Summer Ct",
     "street2": "",
     "street3": "",
     "city": "San Jose",
     "state": "CA",
     "zip": "95122",
     "country": "US",
     "phone": "4159876543",
     "email": "mrshippo@goshippo.com",
     "is_residential": null
  },
  "address_to":{
     "object_id": "0476d70c612a423f9509ba5f807569db",
     "is_complete": true,
     "validation_results": {},
     "name": "Mr Hippo",
     "company": "",
     "street_no": "",
     "street1": "965 Mission St #572",
     "street2": "",
     "street3": "",
     "city": "San Francisco",
     "state": "CA",
     "zip": "94103",
     "country": "US",
     "phone": "4151234567",
     "email": "mrhippo@goshippo.com",
     "is_residential": null
  },
 "address_return":{
     "object_id": "fdabf0abb93c4460b60aa596116872a7",
     "is_complete": true,
     "validation_results": {},
     "name": "Mrs Hippo",
     "company": "Shippo",
     "street_no": "",
     "street1": "1092 Indian Summer Ct",
     "street2": "",
     "street3": "",
     "city": "San Jose",
     "state": "CA",
     "zip": "95122",
     "country": "US",
     "phone": "4159876543",
     "email": "mrshippo@goshippo.com",
     "is_residential": null
  },
 "parcels":[{
     "object_id": "7df2ecf8b4224763ab7c71fae7ec8274",
     "length": "10",
     "width": "15",
     "height": "10",
     "distance_unit": "in",
     "weight": "1",
     "mass_unit": "lb"
  }],
  "shipment_date":"2013-12-03T12:00:00Z",
  "extra":{
     "insurance": {
       "amount": "",
       "currency": ""
     },
     "reference_1":"",
     "reference_2":""
  },
  "alternate_address_to": null,
  "customs_declaration":null,
  "rates": [
       {
           "object_created": "2014-07-17T00:04:06.263Z",
           "object_id": "545ab0a1a6ea4c9f9adb2512a57d6d8b",
           "object_owner": "shippotle@goshippo.com",
           "shipment": "89436997a794439ab47999701e60392e",
           "attributes": [],
           "amount": "5.50",
           "currency": "USD",
           "amount_local": "5.50",
           "currency_local": "USD",
           "provider": "USPS",
           "provider_image_75": "https://cdn2.goshippo.com/providers/75/USPS.png",
           "provider_image_200": "https://cdn2.goshippo.com/providers/200/USPS.png",
           "servicelevel": {
             "name": "Priority Mail",
             "token":"usps_priority",
             "terms": "",
             "extended_token": "usps_priority",
             "parent_servicelevel": null
           },
           "estimated_days": 2,
           "arrives_by": null,
           "duration_terms": "Delivery in 1 to 3 business days.",
           "messages": [],
           "carrier_account": "078870331023437cb917f5187429b093",
           "test": true,
           "zone": "20"
       },
   ],
  "carrier_accounts": [],
  "messages":[],
  "metadata":"Customer ID 123456",
  "test": true
};