export const paymentFields = {
  id: 'ID',
  description: 'Description',
  seller_message: 'Seller Message',
  created: 'Created (UTC)',
  amount: 'Amount',
  amount_refunded: 'Amount Refunded',
  currency: 'Currency',
  converted_amount: 'Converted Amount',
  converted_amount_refunded: 'Converted Amount Refunded',
  fee: 'Fee',
  tax: 'Tax',
  converted_currency: 'Converted Currency',
  status: 'Status',
  statement_descriptor: 'Statement Descriptor',
  customer_id: 'Customer ID',
  customer_description: 'Customer Description',
  customer_email: 'Customer Email',
  captured: 'Captured',
  card_id: 'Card ID',
  invoice_id: 'Invoice ID',
  transfer: 'Transfer',
};
